### ISSUE TITLE
Change BSD license for Apache

### ISSUE THREAD

**Issue by helq** [jhb563/HTensor#2]
Hi @jhb563,

I took your code and I have been extending it. I want to make a pull request to https://github.com/tensorflow/haskell to make dependent types "official" in tensorflow/haskell. [I was asking the tensorflow/haskell devs][issue tfhaskell] how should I (re-)license the code so I can make the PR, and apparently, the easiest way is to dual-license the code under BSD and Apache.

[issue tfhaskell]: https://github.com/tensorflow/haskell/issues/156

So, if everything is alright, could you please change the license of this project to BSD/Apache. It would be awesome, thanks!

**Comment by jhb563** [comment]
@helq Just pushed with `BSDLicense.md` and `ApacheLicense.md`. Does that look good now?

**Comment by helq** [comment]
I think that looks good, I'm in the process of making a Pull Request to the official repo to see if the code gets accepted. Crossed fingers XD

**Comment by helq** [comment]
@jhb563 I didn't get merged in the end but thanks for relicensing!

Happy Holidays!
